# Generated by Django 5.1.2 on 2024-11-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_precioanterior'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
