# Generated by Django 5.1.2 on 2024-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_proveedor_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='clientes_favoritos', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', to='ventas.proveedor'),
        ),
    ]
