# Generated by Django 5.1.2 on 2024-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_cliente_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_tendencia',
            field=models.BooleanField(default=False),
        ),
    ]
